Experiment: experiment_name

# set project and fig paths
project_path: path_to_project
fig_path: path_to_figs

# if loading raw data set raw_data True
raw_data: True
raw_data_path: path to raw data directory.
proc_data_path: path to processed data directory.

# Session info
sessions:
- train
- tone
- context
train_file: # name of training file
tone_file: # name of tone test file
context_file: # name of context test file

# Group info
group_ids: #enter group info (e.g., AAV, condition)
 group1: # list of animals in group1
 group2: # list of animals in group2

sex: True
sex_ids:
 'M': [] # list of males
 'F': [] # list of females