Experiment: 'example_experiment'

# set project and fig paths
project_path: '/Users/kpuhger/miscCode/fear_data/examples/'
fig_path: # path_to_figs

# if loading raw data set raw_data True
raw_data: True
raw_data_path: '/Users/kpuhger/miscCode/fear_data/examples/data-raw'
proc_data_path: # path to processed data directory.

# Session info
sessions:
- train
- tone
- context
train_file: 'TFC_3trial_train_raw.csv'
tone_file: 'TFC_3trial_tone_raw.csv'
context_file: 'TFC_3trial_context_raw.csv'

# Group info
group_ids:
 Group A: ['277', '278', '272', '283']
 Group B: ['257', '258', '273', '284']

sex: True
sex_ids:
 'M': ['257', '258', '272', '273', '277', '278', '283', '284']
 'F': ['']